/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ScionSyncPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// src/sync-service.ts
var import_obsidian = require("obsidian");
var _SyncService = class _SyncService {
  constructor(app, settings, syncState, saveDataFn) {
    this.syncState = {};
    this.debounceTimers = /* @__PURE__ */ new Map();
    this.eventRefs = [];
    this.isSyncing = false;
    this.app = app;
    this.vault = app.vault;
    this.settings = settings;
    this.syncState = syncState || {};
    this.saveDataFn = saveDataFn;
  }
  async initialize() {
    console.log("SyncService: Initializing...");
    try {
      await this.syncAll();
      this.setupFileWatcher();
      console.log("SyncService: Initialization complete");
    } catch (error) {
      console.error("SyncService: Initialization failed", error);
      new import_obsidian.Notice("Scion Sync: Failed to connect to server");
    }
  }
  async syncAll() {
    if (this.isSyncing) {
      console.log("SyncService: Sync already in progress, skipping");
      return;
    }
    this.isSyncing = true;
    try {
      const manifest = await this.fetchManifest();
      const serverFiles = new Map(manifest.files.map((f) => [f.path, f]));
      const localFiles = this.vault.getFiles();
      const localPaths = new Set(localFiles.map((f) => f.path));
      for (const [serverPath, serverRecord] of serverFiles) {
        const localState = this.syncState[serverPath];
        if (!localPaths.has(serverPath)) {
          console.log(`SyncService: Downloading new file: ${serverPath}`);
          await this.downloadFile(serverPath);
        } else if (localState && serverRecord.revision > localState.revision) {
          console.log(`SyncService: Downloading updated file: ${serverPath}`);
          await this.downloadFile(serverPath);
        }
      }
      for (const file of localFiles) {
        const serverRecord = serverFiles.get(file.path);
        const localState = this.syncState[file.path];
        if (!serverRecord) {
          console.log(`SyncService: Uploading new file: ${file.path}`);
          await this.uploadFile(file.path);
        } else if (localState) {
          const currentHash = await this.computeLocalHash(file.path);
          if (currentHash !== localState.hash) {
            console.log(`SyncService: Uploading modified file: ${file.path}`);
            await this.uploadFile(file.path);
          }
        }
      }
      new import_obsidian.Notice("Scion Sync: Sync complete");
    } catch (error) {
      console.error("SyncService: Sync failed", error);
      new import_obsidian.Notice("Scion Sync: Sync failed - check console for details");
    } finally {
      this.isSyncing = false;
    }
  }
  async uploadFile(path) {
    var _a;
    const file = this.vault.getAbstractFileByPath(path);
    if (!(file instanceof import_obsidian.TFile)) {
      console.warn(`SyncService: Cannot upload, file not found: ${path}`);
      return;
    }
    try {
      const content = await this.vault.readBinary(file);
      const base64Content = this.arrayBufferToBase64(content);
      const localState = this.syncState[path];
      const clientRevision = (_a = localState == null ? void 0 : localState.revision) != null ? _a : null;
      const response = await fetch(`${this.settings.serverUrl}/sync`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          path,
          content: base64Content,
          client_revision: clientRevision
        })
      });
      if (response.status === 409) {
        const data = await response.json();
        console.warn(`SyncService: Conflict detected for ${path}`, data);
        await this.handleConflict(path);
        return;
      }
      if (!response.ok) {
        throw new Error(`Upload failed: ${response.status} ${response.statusText}`);
      }
      const result = await response.json();
      this.syncState[path] = {
        hash: result.hash,
        revision: result.revision
      };
      await this.saveSyncState();
      console.log(`SyncService: Uploaded ${path} (revision ${result.revision})`);
    } catch (error) {
      console.error(`SyncService: Failed to upload ${path}`, error);
      throw error;
    }
  }
  async downloadFile(path) {
    try {
      const response = await fetch(`${this.settings.serverUrl}/file/${encodeURIComponent(path)}`);
      if (!response.ok) {
        throw new Error(`Download failed: ${response.status} ${response.statusText}`);
      }
      const content = await response.arrayBuffer();
      const revision = parseInt(response.headers.get("X-File-Revision") || "1", 10);
      const hash = response.headers.get("X-File-Hash") || "";
      const existingFile = this.vault.getAbstractFileByPath(path);
      if (existingFile instanceof import_obsidian.TFile) {
        await this.vault.modifyBinary(existingFile, content);
      } else {
        const folderPath = path.substring(0, path.lastIndexOf("/"));
        if (folderPath && !this.vault.getAbstractFileByPath(folderPath)) {
          await this.vault.createFolder(folderPath);
        }
        await this.vault.createBinary(path, content);
      }
      this.syncState[path] = { hash, revision };
      await this.saveSyncState();
      console.log(`SyncService: Downloaded ${path} (revision ${revision})`);
    } catch (error) {
      console.error(`SyncService: Failed to download ${path}`, error);
      throw error;
    }
  }
  setupFileWatcher() {
    const modifyRef = this.vault.on("modify", (file) => {
      if (file instanceof import_obsidian.TFile) {
        this.debouncedUpload(file.path);
      }
    });
    this.eventRefs.push(modifyRef);
    const createRef = this.vault.on("create", (file) => {
      if (file instanceof import_obsidian.TFile) {
        this.debouncedUpload(file.path);
      }
    });
    this.eventRefs.push(createRef);
    const deleteRef = this.vault.on("delete", (file) => {
      if (file instanceof import_obsidian.TFile) {
        this.handleFileDelete(file.path);
      }
    });
    this.eventRefs.push(deleteRef);
    console.log("SyncService: File watcher setup complete");
  }
  debouncedUpload(path) {
    const existingTimer = this.debounceTimers.get(path);
    if (existingTimer) {
      clearTimeout(existingTimer);
    }
    const timer = setTimeout(async () => {
      this.debounceTimers.delete(path);
      try {
        await this.uploadFile(path);
      } catch (error) {
        console.error(`SyncService: Debounced upload failed for ${path}`, error);
      }
    }, _SyncService.DEBOUNCE_MS);
    this.debounceTimers.set(path, timer);
  }
  async handleFileDelete(path) {
    console.log(`SyncService: File deleted: ${path}`);
    delete this.syncState[path];
    await this.saveSyncState();
  }
  async handleConflict(originalPath) {
    try {
      const lastDot = originalPath.lastIndexOf(".");
      const ext = lastDot !== -1 ? originalPath.substring(lastDot) : "";
      const base = lastDot !== -1 ? originalPath.substring(0, lastDot) : originalPath;
      const conflictPath = `${base} (Conflict)${ext}`;
      const response = await fetch(
        `${this.settings.serverUrl}/file/${encodeURIComponent(originalPath)}`
      );
      if (!response.ok) {
        throw new Error(`Failed to download conflict file: ${response.status}`);
      }
      const content = await response.arrayBuffer();
      const revision = parseInt(response.headers.get("X-File-Revision") || "1", 10);
      const hash = response.headers.get("X-File-Hash") || "";
      const existingConflict = this.vault.getAbstractFileByPath(conflictPath);
      if (existingConflict instanceof import_obsidian.TFile) {
        await this.vault.modifyBinary(existingConflict, content);
      } else {
        const folderPath = conflictPath.substring(0, conflictPath.lastIndexOf("/"));
        if (folderPath && !this.vault.getAbstractFileByPath(folderPath)) {
          await this.vault.createFolder(folderPath);
        }
        await this.vault.createBinary(conflictPath, content);
      }
      this.syncState[originalPath] = { hash, revision };
      await this.saveSyncState();
      const fileName = originalPath.substring(originalPath.lastIndexOf("/") + 1);
      new import_obsidian.Notice(`Scion Sync: Conflict in "${fileName}". Remote version saved as "${fileName.replace(ext, ` (Conflict)${ext}`)}"`);
      console.log(`SyncService: Conflict resolved for ${originalPath} \u2192 ${conflictPath}`);
    } catch (error) {
      console.error(`SyncService: Failed to handle conflict for ${originalPath}`, error);
      new import_obsidian.Notice(`Scion Sync: Failed to resolve conflict for ${originalPath}`);
    }
  }
  async computeLocalHash(path) {
    const file = this.vault.getAbstractFileByPath(path);
    if (!(file instanceof import_obsidian.TFile)) {
      throw new Error(`File not found: ${path}`);
    }
    const content = await this.vault.readBinary(file);
    const hashBuffer = await crypto.subtle.digest("SHA-256", content);
    return this.arrayBufferToHex(hashBuffer);
  }
  async fetchManifest() {
    const response = await fetch(`${this.settings.serverUrl}/manifest`);
    if (!response.ok) {
      throw new Error(`Failed to fetch manifest: ${response.status}`);
    }
    return response.json();
  }
  async saveSyncState() {
    await this.saveDataFn({ syncState: this.syncState });
  }
  arrayBufferToBase64(buffer) {
    const bytes = new Uint8Array(buffer);
    let binary = "";
    for (let i = 0; i < bytes.byteLength; i++) {
      binary += String.fromCharCode(bytes[i]);
    }
    return btoa(binary);
  }
  arrayBufferToHex(buffer) {
    const bytes = new Uint8Array(buffer);
    return Array.from(bytes).map((b) => b.toString(16).padStart(2, "0")).join("");
  }
  destroy() {
    for (const timer of this.debounceTimers.values()) {
      clearTimeout(timer);
    }
    this.debounceTimers.clear();
    for (const ref of this.eventRefs) {
      this.vault.offref(ref);
    }
    this.eventRefs = [];
    console.log("SyncService: Destroyed");
  }
};
_SyncService.DEBOUNCE_MS = 2e3;
var SyncService = _SyncService;

// src/main.ts
var DEFAULT_SETTINGS = {
  serverUrl: "http://localhost:3000"
};
var ScionSyncPlugin = class extends import_obsidian2.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
    this.syncService = null;
    this.syncState = {};
  }
  async onload() {
    await this.loadSettings();
    console.log("Scion Sync plugin loaded");
    this.syncService = new SyncService(
      this.app,
      this.settings,
      this.syncState,
      async (data) => {
        this.syncState = data.syncState;
        await this.saveData({ settings: this.settings, syncState: this.syncState });
      }
    );
    this.syncService.initialize();
    this.addSettingTab(new ScionSyncSettingTab(this.app, this));
    this.addRibbonIcon("refresh-cw", "Scion Sync", async () => {
      var _a;
      console.log("Manual sync triggered");
      await ((_a = this.syncService) == null ? void 0 : _a.syncAll());
    });
    this.addCommand({
      id: "sync-now",
      name: "Sync Now",
      callback: async () => {
        var _a;
        console.log("Sync command executed");
        await ((_a = this.syncService) == null ? void 0 : _a.syncAll());
      }
    });
  }
  onunload() {
    var _a;
    (_a = this.syncService) == null ? void 0 : _a.destroy();
    console.log("Scion Sync plugin unloaded");
  }
  async loadSettings() {
    const data = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, data == null ? void 0 : data.settings);
    this.syncState = (data == null ? void 0 : data.syncState) || {};
  }
  async saveSettings() {
    await this.saveData({ settings: this.settings, syncState: this.syncState });
  }
};
var ScionSyncSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian2.Setting(containerEl).setName("Server URL").setDesc("The URL of your Scion sync server (e.g., http://192.168.1.100:3000)").addText(
      (text) => text.setPlaceholder("http://localhost:3000").setValue(this.plugin.settings.serverUrl).onChange(async (value) => {
        this.plugin.settings.serverUrl = value;
        await this.plugin.saveSettings();
      })
    );
  }
};
